### ISSUE TITLE
The mouse cursor disappears.

### ISSUE THREAD

**Issue by Kin-Tal** [ds5678/TimeAccelerator#1]
When I connect the mod (even without other mods), the mouse cursor disappears when the new game starts or load save.

**Comment by ds5678** [comment]
I am nearly certain I have nothing to do with your experience.

**Comment by Kin-Tal** [comment]
I checked everything. It is this mod that does this. I have no idea how. Can I give any evidence?

**Comment by ds5678** [comment]
The mod is fairly simple. You are welcome to investigate.

**Comment by Kin-Tal** [comment]
Hoo. Simple, but games are a fragile mountain of code. Put the texture at the wrong angle, and now the game is already being crushed.
At the expense of the bug. The mouse cursor disappears in all tabs. Even in the pause menu. But nothing changes in the gameplay. I still see what I'm picking up.

**Comment by Kin-Tal** [comment]
![vvv](https://user-images.githubusercontent.com/63497810/223067728-a9279c08-8b05-4420-86c3-58e40fbc76c9.png)
Here.

**Comment by Kin-Tal** [comment]
![изображение](https://user-images.githubusercontent.com/63497810/223068194-e42f09f9-33f8-42ee-b9d1-366f141efcd4.png)
The latest Steam version.

**Comment by ds5678** [comment]
I could not reproduce.

> You are welcome to investigate.

I meant that you could compile the mod yourself and make changes.

**Comment by Kin-Tal** [comment]
Sorry. I'm not ready for such feats ::::D
